version: "3.8"
services:
  web:
    image: ghcr.io/redcloud442/elevateglobal:prod
    environment:
      NEXT_PUBLIC_SUPABASE_URL: /run/secrets/supabaseUrl
      NEXT_PUBLIC_SUPABASE_ANON_KEY: /run/secrets/anonKey
      NEXT_PUBLIC_BASE_URL: /run/secrets/baseUrl
      SUPABASE_SERVICE_ROLE_KEY: /run/secrets/serviceRoleKey
      DATABASE_URL: /run/secrets/databaseUrl
      DIRECT_URL: /run/secrets/directUrl
      UPSTASH_REDIS_REST_URL: /run/secrets/redisUrl
      UPSTASH_REDIS_REST_TOKEN: /run/secrets/redisToken
      RESEND_API_KEY: /run/secrets/resendKey
      MOVIDER_API_KEY: /run/secrets/moviderKey
      MOVIDER_API_SECRET: /run/secrets/moviderSecret
    secrets:
      - databaseUrl
      - directUrl
      - supabaseUrl
      - anonKey
      - serviceRoleKey
      - baseUrl
      - redisUrl
      - redisToken
      - resendKey
      - moviderKey
      - moviderSecret
    deploy:
      mode: replicated
      replicas: 5
      update_config:
        order: start-first
    ports:
      - "8080:8080"

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run
    networks:
      - public
    secrets:
      - tunnelKey
    environment:
      - TUNNEL_TOKEN=/run/secrets/tunnelKey
    deploy:
      replicas: 2

secrets:
  databaseUrl:
    external: true
  directUrl:
    external: true
  supabaseUrl:
    external: true
  anonKey:
    external: true
  serviceRoleKey:
    external: true
  baseUrl:
    external: true
  tunnelKey:
    external: true
  redisUrl:
    external: true
  redisToken:
    external: true
  resendKey:
    external: true
  moviderKey:
    external: true
  moviderSecret:
    external: true

networks:
  public:
    external: true
